### ISSUE TITLE
when there is no qos configure, and try to remove the list under qos, libnetconf will add qos

### ISSUE THREAD

**Issue by jinxud** [CESNET/libnetconf#103]
hi,

there is no any configure relate to qos on the device, then try to remove qos with below rpc message:

    <?xml version='1.0' encoding='UTF-8'?>
    <rpc message-id="0"
    xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:eqos="urn:ietf:params:xml:ns:yang:qos">
     <edit-config>
             <target>
                        <running />
              </target>  
               <config>  
                        <eqos:qos >
                               <eqos:class-definition xc:operation="remove">
                                      <eqos:class-definition>1</eqos:class-definition>
                                      <eqos:qos>
                                              <eqos:dscp-value>12</eqos:dscp-value>
                                                <eqos:class>a</eqos:class>
                                        </eqos:qos>
                                      <eqos:qos>
                                               <eqos:dscp-value>10</eqos:dscp-value>
                                             <eqos:class>2</eqos:class>
                                        </eqos:qos>
                            </eqos:class-definition>
                    </eqos:qos>
               </config>
       </edit-config>
    </rpc>
    ]]>]]>

libnetconf will add qos: below is the old_doc and new_doc

old_doc
<?xml version="1.0"?>

new_doc
<?xml version="1.0"?>
<eqos:qos xmlns:eqos="urn:ietf:params:xml:ns:yang:qos"/>

then will add qos
<qos:ADD:1:0>
</qos:ADD:1:0>

is it cause by : remove not at the top level. and libnetconf find there is new node: qos. then will add it?

Thanks,
Jin

**Comment by jinxud** [comment]
update the rpc message:

<?xml version='1.0' encoding='UTF-8'?>
<rpc message-id="0"
		xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
		xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
		xmlns:eqos="urn:ietf:params:xml:ns:yang:qos">
	<edit-config>
		<target>
			<running />
		</target>  
		<config>  
			<eqos:qos >
				<eqos:class-definition xc:operation="remove">
					<eqos:class-definition>1</eqos:class-definition>
					<eqos:qos>
						<eqos:dscp-value>12</eqos:dscp-value>
						<eqos:class>a</eqos:class>
					</eqos:qos>
					<eqos:qos>
						<eqos:dscp-value>10</eqos:dscp-value>
						<eqos:class>2</eqos:class>
					</eqos:qos>
				</eqos:class-definition>
			</eqos:qos>
		</config>
	</edit-config>
</rpc>
]]>]]>

**Comment by michalvasko** [comment]
Hi Jin,

in very short, if you add an 's' at the end of the container to be removed (class-definitions instead of class-definition) your problem should be solved.

To elaborate a bit, what you experienced should not be happening. I tried debugging it, but failed. Firstly, I could not find the model you're using, I think it's not available anymore and so I used what I believed to be an updated version from [a draft](https://tools.ietf.org/html/draft-chen-rtgwg-qos-yang-00). But even then I failed to load it into libnetconf because it contains an invalid XPath expression. I have no reason to believe that the model you're using is any better and the time spent correcting the model and debugging this issue does not seem to be worth it to me right now. I may look at this once the model is updated and actually valid.

Regards,
Michal

**Comment by jinxud** [comment]
Hi,

but from the model, it is class-definition, not class-definitions. below is part of model related to this problem. If I put the operation to <eqos:qos > this level, it is no problem

  container qos {
    presence "";
    description "Configure Global QoS parameters ";
    list class-definition {
      key "class-definition";
      description   "Configure packet class definitions ";
      leaf class-definition {
        type string {
          length "0..39";
        }
        description "QoS class definition name ";
      }
      uses class-definition-grp;
}
}


Thanks,
Jin

**Comment by jinxud** [comment]
Hi,

I use the updated rpc message according to your suggestion, still not work. same as before.

    <?xml version='1.0' encoding='UTF-8'?>
    <rpc message-id="0"
    xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
    xmlns:eqos="urn:ietf:params:xml:ns:yang:qos">
     <edit-config>
         <target>
                    <running />
          </target>  
           <config>  
                    <eqos:qos >
                           <eqos:class-definitions xc:operation="remove">   ---- add s
                                  <eqos:class-definition>1</eqos:class-definition>
                                  <eqos:qos>
                                          <eqos:dscp-value>12</eqos:dscp-value>
                                            <eqos:class>a</eqos:class>
                                    </eqos:qos>
                                  <eqos:qos>
                                           <eqos:dscp-value>10</eqos:dscp-value>
                                         <eqos:class>2</eqos:class>
                                    </eqos:qos>
                        </eqos:class-definitions>  ------> add s
                </eqos:qos>
           </config>
    </edit-config>
    </rpc>
    ]]>]]>


Thanks,
Jin

**Comment by michalvasko** [comment]
Hi Jin,

I made the effort, modified the ietf-qos model and it worked as expected. So, in order for me to be able to help you, you need to upload the model you're using ("urn:ietf:params:xml:ns:yang:qos") somewhere I can get to it (I could not find it anywhere). Or use the one from the draft I linked in my previous post, but you will need to make it valid first yourself, but in that one it worked correctly for me.

Regards,
Michal

**Comment by jinxud** [comment]
Hi Michal

below is the model file:

        module qos {
          yang-version "1";
        
          namespace "urn:ietf:params:xml:ns:yang:qos";
        
          prefix "eqos";
        
          organization "abc";
          contact "Web:   <http://www.abc.com>";
        
          description 
            "qos Copyright (c) 2015 AB.
             All rights reserved";
        
          revision "2015-08-19" {
            description   "initial revision";
            reference "rfc6020.txt.";
          }
        
          grouping class-definition-grp {
            description "QoS class definition configuration mode";
          
            list qos {
              key "dscp-value";
              max-elements 64;
              description   "internal packet-descriptor priority and "
              + "precedence ";
              leaf dscp-value {
                type uint8 {
                  range "0..63";
                }
                description "Differentiated services codepoint value ";
              }
              leaf class {
                type string {
                  length "0..39";
                }
                mandatory true;
                description "specify the class for packets with this pd- "
                + "value QoS class definition class name ";
              }
            }
        
          }
        
          container qos {
            presence "";
            description "Configure Global QoS parameters ";
            list class-definition {
              key "class-definition";
              description   "Configure packet class definitions ";
              leaf class-definition {
                type string {
                  length "0..39";
                }
                description "QoS class definition name ";
              }
              uses class-definition-grp;
            }
            list policy {
              key "gpol-polname";
              description   "Configure Global QoS policy ";
              leaf gpol-polname {
                type string {
                  length "0..39";
                }
                description "QoS policy name ";
              }
        
            }
            list profile {
              key "profile-name";
              description   "Configure Global QoS profile ";
              leaf profile-name {
                type string {
                  length "0..39";
                }
                description "QoS profile name ";
              }
        
            }
        
            list class-map {
              key "map-name";
              description   "Configure packet classification mapping ";
              leaf map-name {
                type string;
                description "QoS classification map name ";
              }
            }
          }
        }
 

Thanks for your support.

Jin

**Comment by michalvasko** [comment]
Hi Jin,

I tried to send the RPC from your first message (using netopeer-cli) and the running configuration in Netopeer was left with a newly created empty container `<eqos:qos xmlns:eqos="urn:ietf:params:xml:ns:yang:qos"/>` exactly as expected. Now that I think about it I may have misunderstood what you consider the issue to be. I though that some of those list instances in the `class-definition` node get added, but you meant the top-level container, just like it happened in my case, right? There is no operation on that node, so it is the default merge - it must be created. Next time please specify your problem exactly and first make sure it really is a problem.

Regards,
Michal

**Comment by jinxud** [comment]
Michal,

Thanks for your response. 

Jin

**Comment by rkrejci** [comment]
Just to make it more clear - in this case, the top level element `qos` has implicit `merge` operation so it is merged with (created in) the original (empty) datastore. The `class-definition` element is marked to be removed but it isn't present in the original datastore (it is empty). The `remove` operation is silent when the targeted data does not exist so nothing happened with this `remove` request. If you would use the `delete` operation, you should get error reply because the missing target data matters in case of `delete` operation.

**Comment by jinxud** [comment]
Thanks a lot. it is clear for me
